INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(1, 'NA','','NA')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(2, 'Task Owner','','TWNR')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(3, 'Task Members','','TMEM')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(4, 'Task Creator','','TCRTR')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(5, 'Module All','','MAll')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(6, 'Project All','','PAll')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(7, 'Group All','','GAll')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(8, 'Task On-Behalf','','TONBF')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(9, 'Module Creator','','MCRTR')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(10, 'Module Write','','MWrite')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(11, 'Module Read','','MRead')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(12, 'Project Write','','PWrite')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(13, 'Project Read','','PRead')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(14, 'Project Creator','','PCRTR')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(15, 'Group Creator','','GCRTR')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(16, 'Group Heads','','GHeads')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(17, 'Group Read','','Gread')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(18, 'Task Inform-To','','TINFT')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(19, 'Project Module All','','PMAll')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(20, 'Project Module Write Users','','PMWrite')
INSERT INTO email_recipient_master (email_recipient_syscode, email_recipient_name, [description], code)
VALUES(21, 'Project Module Read Users','','PMRead')
