INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(1, 'Workflow Creation','','WFC')
INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(2, 'Workflow Updation','','WFU')
INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(3, 'Project Creation','','PC')
INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(4, 'Project Updation','','PU')
INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(5, 'Module Creation','','MC')
INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(6, 'Module Updation','','MU')
INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(7, 'Task Creation','','TC')
INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(8, 'Task Updation','','TU')
INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(9, 'Task Status Change','','TSC')
INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(10, 'Task Weightage Change','','TWC')
INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(11, 'Task Member Update','','TMU')
INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(12, 'Task Inform To','','TINFT')
INSERT INTO email_type_master (email_type_syscode, email_type_name, [description], code)
VALUES(13, 'Task Creation Workflow Task Parent','','TCWFP')



