insert into environment_master (group_syscode, env_name,env_code, env_desc,created_by,is_active,is_deleted)
values (1,'Build','BLD','Build environment for unit testing for developers', 3986,1,0),
		(1,'UAT','UAT','UAT environment for testing by testers', 3986,1,0),
		(1,'PreProd','PP','PreProd environment for testing before going Live', 3986,1,0),
		(1,'LIVE','LIV','Live environment for Live release', 3986,1,0)


INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'Application Name ', 'This is Web Application Name','0','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'Application URL', 'This is Web Application URL','0','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'Application IIS Site Name', 'This Site name in the IIS server','0','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'API Name', 'API Name','0','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'API URL', 'API URL','0','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'API IIS Site Name', 'API IIS Site Name','0','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'Database Name', 'Database Name','0','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'Web Server IP ', 'Web Server IP ','0','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'API Server IP', 'API Server IP','0','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'DB Server IP', 'DB Server IP','0','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'Notes', 'Any additional information','0','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'TFS URL', 'TFS Collection Path','0','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'Release Folder Path', 'Release Folder Path','1','varchar',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'Backup Application', 'Backup Application','1','bit',3986)
INSERT INTO project_parameter_master (group_syscode,parameter_name,parameter_desc, editable_in_release,parameter_datatype,created_by)
 VALUES(1, 'Backup Database', 'Backup Database','1','bit',3986)
